### ISSUE TITLE
Insights into the methodology

### ISSUE THREAD

**Issue by ralphlauran99** [gabmoreira/maks#1]
Hi,
First of all thanks for the code, I've tested it out, it seems to work well. I've used it to estimate global rotation and translation (which would map a 3d coordinate from world to cam) from relative rotation/translation(which would map a point from image 1 to image2) of image pairs (estimated from epipolar geometry) I've had to invert the relative Rigid body transformation before converting it into the g2ofile and  passing it as an input to maks to get global transformations which seem to be very reasonable.

I was wondering if you could share the paper as and when it becomes available, or any other resource which would help me better understand how the pose-graph optimization is being done. 

Thanks again.

**Comment by gabmoreira** [comment]
Hello Ralph,

Thank you for the feedback. This is still an ongoing project so there may
be some minor issues. I'm glad you were able to get it working.
The paper will appear in WACV 2021. You can find a preprint here:
http://isr.tecnico.ulisboa.pt/~gmoreira/docs/1140.pdf

If you have any questions, let me know.

Gabriel

**Comment by ralphlauran99** [comment]
Thanks, will get back to you :)
